require:
  - rubocop-rspec
  - rubocop-rails

RSpec/AnyInstance:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Max: 45

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/AbcSize:
  Max: 25

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'spec/rails_helper.rb'
