require:
  - rubocop-rspec
  - rubocop-rails

Rails/OutputSafety:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 30
  ExcludedMethods: ['describe']

Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Max: 45

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/AbcSize:
  Max: 25

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'test/**/*'
    - 'spec/rails_helper.rb'
