require:
  - rubocop-rspec
  - rubocop-rails

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/features/**/*'

RSpec/AnyInstance:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'app/admin/**/*'

Style/ClassAndModuleChildren:
  Enabled: false

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'spec/rails_helper.rb'
